session_name: Plugins
start_directory: ~/Code/
windows:
  - window_name: php-dev-tools
    start_directory: ~/Code/php-dev-tools.nvim/
    panes:
      - shell_command:
        - cmd: 'c'
  - window_name: telescope-env
    start_directory: ~/Code/telescope-env/
    panes:
      - shell_command:
        - cmd: 'c'
  - window_name: t-sessions
    start_directory: ~/Code/t-session/
    panes:
      - shell_command:
        - cmd: 'c'
