session_name: Whiplash
start_directory: "~/Code/whiplash-middleware"
windows:
  - window_name: Project
    panes:
      - shell_command:
        - cmd: 'c'
  - window_name: Terminals
    panes:
      - shell_command:
        - cmd: 'c'
